"""Create Login Model

Revision ID: c8fd15a40c8c
Revises: eb50f3abffcd
Create Date: 2023-06-08 12:23:33.280121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8fd15a40c8c'
down_revision = 'eb50f3abffcd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('verification_token', sa.UUID(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('verification_token'),
    schema='shared'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order', schema='tenant')
    op.drop_table('product', schema='tenant')
    op.drop_table('note', schema='tenant')
    op.drop_table('tenant', schema='shared')
    op.drop_table('login', schema='shared')
    op.drop_table('book', schema='shared')
    # ### end Alembic commands ###
