"""Create Order Model

Revision ID: eb50f3abffcd
Revises: a26047ac2dd5
Create Date: 2023-06-06 19:39:58.552040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb50f3abffcd'
down_revision = 'a26047ac2dd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('client', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['tenant.product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid'),
    schema='tenant'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order', schema='tenant')
    op.drop_table('product', schema='tenant')
    op.drop_table('note', schema='tenant')
    op.drop_table('tenant', schema='shared')
    op.drop_table('book', schema='shared')
    # ### end Alembic commands ###
